sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_1.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_2.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_3.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_4.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_5.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_6.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_7.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_8.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_9.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_10.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_11.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_12.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_13.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_14.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_15.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_16.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_17.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_18.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_19.txt
sbt "run --run examples/policy_act_until_done.jitd" > /Users/darshanabalakrishnan/Desktop/JITD_GitHub/jitd-synthesis/segfault_check/run_20.txt